import '../styles/globals.css'
import { Layout } from '../components/layouts/Layout'

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className="dark:bg-gray-800">
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
